[package]
name = "clump_finding"
version = "0.1.0"
authors = ["Hector Corrada Bravo <hcorrada@gmail.com>"]

[dependencies]
scan_fmt = "0.1.0"
itertools = "0.3.0"

[dependencies.rosalind_lib]
path = "../rosalind_lib"
